### PR TITLE
Add webpack-dev-server-firewall

### PR DESCRIPTION
**Pull request by igoradamenko**
Hello!

We've created the package a year ago and used it in the company for tens of our projects. So, we've open sourced it and decided to add it to the list because as we think it's quite useful.

The package prevents uncontrollable access to dev server by asking manual approve from the developer when someone connects to the server from unknown IP.

More details in the repo: https://github.com/funbox/webpack-dev-server-firewall

A small article with an explanation: https://dev.to/igoradamenko/protect-your-dev-server-gob

### CODE REVIEW

**Comment by alexander-akait** [comment]
Just interesting, webpack-dev-server has the `allowedHosts` option, what is the problem? why do not use it?

**Comment by igoradamenko** [comment]
Hi, @evilebottnawi!

The problem is the difference in use cases.

`allowedHosts` works only for the requests that has `Host` header that isn't equal to IP or `localhost`. Otherwise webpack-dev-server doesn't even check the host, it approves the connection instantly:

https://github.com/webpack/webpack-dev-server/blob/89ffb86cd26425c59e3937ca06a2c804a01b8f1d/lib/Server.js#L884

Our package works when you want to use `host: '0.0.0.0'` to make the server public in the local network (which is highly popular decision: [SO](https://stackoverflow.com/questions/35412137/how-to-get-access-to-webpack-dev-server-from-devices-in-local-network), [GitHub](https://github.com/search?p=1&q=%22devServer+host%22+filename%3Awebpack.config.js+filename%3Awebpack.config.dev.js+filename%3Awebpack.js+language%3AJavaScript+language%3AJavaScript&type=Code), [Google](https://www.google.com/search?q=webpack+dev+server+host+0.0.0.0)), and all the connections from this network have hostnames equals to their IPs (which is usual when you or someone else connects to the server by IP). In this case you can't filter such connections using webpack-dev-server options.

`allowedHosts` option allows to receive requests from _the listed domains_, because by default the server allows the requests from `localhost` and IPs only. Which is not our case.

**Comment by alexander-akait** [comment]
Thanks for clarify

**Review by alexander-akait — APPROVED** [review]

**Comment by igoradamenko** [comment]
Not sure what I should do with CLA CI check. I've surely signed the agreement.

image

I guess it's just slow?

**Comment by igoradamenko** [comment]
@evilebottnawi, yay! I've fixed the problem with CLA CI :-)

It looks like it didn't work because I edited README using web UI and the email in the commit wasn't the same as the mail I used when signed the CLA. So, I've edited the commit and force pushed the branch.

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
