### PR TITLE
docs: add `exif-loader`

### PR DESCRIPTION
**Pull request by herschel666**

### CODE REVIEW

**Comment by jeffin143** [comment]
@herschel666 , could you sign the cla :)

**Review by jeffin143 — APPROVED** [review]
Lgtm

**Comment by herschel666** [comment]
@jeffin143 I signed it, like the badge in the first comment says, and I also can't change that anymore. Don't know what's wrong with the CI state…

**Comment by alexander-akait** [comment]
Please accept CLA

**Comment by herschel666** [comment]
@evilebottnawi as I already wrote: I signed it!

cla

[`comment-565971611`](#issuecomment-565971611)

**Comment by alexander-akait** [comment]
Done

**Pull request merged**
