### PR TITLE
Added Webpack 2 book for beginners

### PR DESCRIPTION
**Pull request by shalotelli**
Released a guide titled "Webpack 2 - A Build Tool for Modern JavaScript Applications" and added to Books section. Not entirely sure how you guys feel about this as SurviveJS is already awesome but thought it would add some variety to the section.

### CODE REVIEW

**Comment by TheLarkInn** [comment]
@d3viant0ne How do we want to handle situations where plugin, book, etc author wants to add their own work. I believe @sindresorhus has guidelines for age and maturity of material, or maybe that only applies to repositories. 

@shalotelli If you are selling this work, I would best also check with the [JS Foundation](https://js.founation/) who owns the rights to our logos, and media. See github.com/webpack/media for more information.

**Comment by TheLarkInn** [comment]
cc @bebraw

**Comment by sindresorhus** [comment]
> I believe @sindresorhus has guidelines for age and maturity of material, or maybe that only applies to repositories.

I have a rule in my lists that requires something to be at least 30 days old. This is meant to reduce hit'n'run entries (ones that never gets maintained after submission), but it's really up to each individual list to decide.

**Comment by joshwiens** [comment]
@TheLarkInn - I have no issue with people adding their own work, I do on the other hand follow @sindresorhus's guidelines for the `maturity` of a plugin / video / book / blog.

The other issue being this is `awesome-webpack` not `all-the-things-webpack` and not every pull request opened is accepted. I've looked at every lib, read every blog, watched every video & flipped through every book that made it's way onto this list. 

When it comes to closed source publications where a determination on the `awesome` factor is limited to a two page snippet, I don't have a great deal to go on.

**Comment by shalotelli** [comment]
@d3viant0ne @TheLarkInn i would be more than happy to send you a copy of the guide for you to look over to determine whether it fits this list. In fact any feedback I would get would be invaluable not only for the quality of the guide but also for me personally. Shoot me your email and I'll get a link out to you guys

**Comment by sukrosono** [comment]
It's more than 4 month now.

**Pull request closed without merging**
