### PR TITLE
docs(#articles): correct broken links

### PR DESCRIPTION
**Pull request by xxjinwei**

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
Thank you!

**Comment by xxjinwei** [comment]
commited with my work email 😿

**Review by michael-ciniawsky — APPROVED** [review]
@xxjinwei Thx

**Comment by joshwiens** [comment]
CLA has to be signed before this is merged

**Comment by sukrosono** [comment]
i see the cla show green, marked as signed. So many PR opened, can we merge this one?

**Comment by joshwiens** [comment]
Done :)

**Pull request merged**
