### PR TITLE
Added Webpack Academy in courses.

### PR DESCRIPTION
**Pull request by dhavalchaudhary**

### CODE REVIEW

**Comment by joshwiens** [comment]
//cc @TheLarkInn - For reference, this really isn't intended to be `by` Sean.

**Comment by TheLarkInn** [comment]
@d3viant0ne @dhavalchaudhary 

Right now it is pending between `by me` and `by webpack` based upon platform developments. For now, lets just leave the `by` section off, and then I will followup and add the finishing details after next week.

**Comment by TheLarkInn** [comment]
Thank you so much @dhavalchaudhary

**Comment by dhavalchaudhary** [comment]
Welcome

**Pull request merged**
