### PR TITLE
Add prerender-spa-plugin to Plugins section

### PR DESCRIPTION
**Pull request by chrisvfritz**

### CODE REVIEW

**Comment by joshwiens** [comment]
Need this to not wrap. Personally I'd start with `Plugin` in the title as it's under the plugins section and tweak from there.

screen shot 2017-01-23 at 6 41 11 pm


Cool plugin btw :) It's not something I'd seen before.

**Comment by kentcdodds** [comment]
screen shot 2017-01-24 at 10 15 21 pm

LGTM!

**Comment by chrisvfritz** [comment]
Thanks! 🙂 Just shortened the entry.

**Comment by kentcdodds** [comment]
Looks like I can't merge in this repo anymore :man_shrugging:

**Comment by joshwiens** [comment]
@kentcdodds - It's being prepped to move over to webpack-contrib. Once it's in place everyones permissions will be put back in place

**Pull request merged**
