### PR TITLE
Add sass-webpack-plugin

### PR DESCRIPTION
**Pull request by jalkoby**
I've made a sass plugin which takes a different approach to work with sass. Think it will work for other people as well.

PS.  contributing.md has an artefact so I've fixed this file too.

### CODE REVIEW

**Comment by jalkoby** [comment]
any progress?

**Comment by elektronik2k5** [comment]
@jalkoby I gotta say that I've read the description in your project readme a few times, and I don't understand how exactly it's better than the standard `sass-loader`. What does it save? The loader config?

**Comment by jalkoby** [comment]
@elektronik2k5 thanks for the hint about the description. The core idea is simplicity adding sass into webpack. A user doesn't need to add extra loader like "style-loader" + "css-loader". The import process works much better as it's a fully native solution (not a patch to work well with webpack). And it's a production ready from the beginning unlike sass-loader which says adds +1 plugin for that ("Usually, it's recommended to extract the style sheets into a dedicated file in production using the ExtractTextPlugin.")

**Comment by elektronik2k5** [comment]
@jalkoby sounds cool! You should update the readme to clearly state those, or even make a side by side comparison or some other way of clearly communicating the value of your solution.

**Comment by jalkoby** [comment]
@elektronik2k5 the readme is updated. What do you think about it?

**Comment by joshwiens** [comment]
This is going to sound a bit prudish which is funny coming from me but this would be deemed inappropriate by some people.

screen shot 2017-04-20 at 1 42 21 am

**Comment by joshwiens** [comment]
- This isn't a collection of everything, it's a collection of `awesome` and part of that description per the parent repo requires a level of maturity for anything being added. 

To that end, `https://github.com/jalkoby/sass-webpack-plugin` doesn't belong here ( yet :) ). Give it time to mature a bit and we can revisit adding it.

**Comment by jalkoby** [comment]
Np, thanks for feedback

**Comment by elektronik2k5** [comment]
@jalkoby much better, thanks! :)

**Pull request closed without merging**
