### PR TITLE
Add webpack-require-from plugin

### PR DESCRIPTION
**Pull request by agoldis**

### CODE REVIEW

**Comment by agoldis** [comment]
@ericclemmons @d3viant0ne please :)

**Comment by ericclemmons** [comment]
@agoldis I don't have merge rights :( @webpack-contrib/org-maintainers

**Comment by agoldis** [comment]
@evilebottnawi trying to get some attention here, any chance?

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Please rebase

**Comment by agoldis** [comment]
@evilebottnawi done

**Pull request merged**
