### PR TITLE
docs(README): add `webpack-pwa-manifest` plugin

### PR DESCRIPTION
**Pull request by arthurbergmz**
It's a plugin for generating a manifest.json for Progressive Web Apps, based on the user's options.

### CODE REVIEW

**Comment by joshwiens** [comment]
@arthurbergmz - Need you to trim down that description enough so the line doesn't wrap.

**Review by arthurbergmz — COMMENTED** [review]
Short description

**Review by arthurbergmz — COMMENTED** [review]
Shorter title and description

**Review by michael-ciniawsky — APPROVED** [review]
@arthurbergmz thx

**Comment by joshwiens** [comment]
If I might offer an unrelated observation, as a consumer not having a `changelog.md` or github tags with release notes makes catching up with a projects changes from version to version a bit taxing.

Something to consider :)

**Pull request merged**
