### PR TITLE
Added bin-exec-loader

### PR DESCRIPTION
**Pull request by milewski**
I'm not really sure which category this better fits in... what it does.. is get any file -> pipe to any binary -> get its result -> gives back to webpack.. i found myself using it a lot .. specially it allows me to quickly create tools with node to be used as a loader with an easy to use in/out interface

https://github.com/milewski/bin-exec-loader

### CODE REVIEW

**Comment by sukrosono** [comment]
any problem with this one? it's not merged since April.

**Comment by elektronik2k5** [comment]
@milewski can you please resolve the conflict? Your loader looks really cool and IMO should be in the list.

**Comment by milewski** [comment]
@elektronik2k5 resolved and i also have updated dependencies on the repo and fixed build error on Travis... but i'm hopeless this will get merged anytime soon 🐌

**Comment by elektronik2k5** [comment]
@d3viant0ne can you please review this PR?

**Pull request merged**
