### PR TITLE
Add fork-ts-checker-webpack-plugin

### PR DESCRIPTION
**Pull request by bodadotsh**
Name: `fork-ts-checker-webpack-plugin`
Description: Webpack plugin that runs typescript type checker on a separate process.
Repo: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin
NPM: https://www.npmjs.com/package/fork-ts-checker-webpack-plugin (23M downloads/month)

### CODE REVIEW

**Comment by bodadotsh** [comment]
@evilebottnawi I've signed my CLA, any idea why the bot is not updated?

**Review by alexander-akait — APPROVED** [review]
Thanks!

**Comment by alexander-akait** [comment]
@bodazhao You need to use the same email in commit in CLA

**Comment by bodadotsh** [comment]
Rebase fixed the CLA issue 🎉 @evilebottnawi

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Thanks

**Pull request merged**
